"""Build a shareable Markdown report for a single-stock deep dive.

Pure string assembly (no I/O), so it's easy to test and the dashboard can hand
the result straight to a download button. Markdown prints cleanly to PDF from
any browser/editor.
"""

from __future__ import annotations

from typing import Optional

_DOT = {"positive": "🟢", "negative": "🔴", "neutral": "⚪"}


def build_report_md(
    symbol: str,
    timeframe: str,
    *,
    pattern: Optional[str] = None,
    confidence: Optional[str] = None,
    edge: Optional[str] = None,
    entry=None,
    stop=None,
    target=None,
    rr=None,
    size=None,
    debt_status: Optional[str] = None,
    highlights: Optional[list] = None,
    news: Optional[list] = None,
    thesis: Optional[str] = None,
) -> str:
    """Compose a Markdown report from the deep-dive pieces (any may be omitted)."""
    L = [f"# {symbol} — EdgeForge report", f"*{timeframe} timeframe*", ""]

    if pattern:
        L.append("## Pattern")
        head = f"- **{pattern}**"
        if confidence:
            head += f" — {confidence}"
        L.append(head)
        if edge:
            L.append(f"- Historical edge: {edge}")
        L.append("")

    if entry is not None:
        L.append("## Trade plan")
        L.append(f"- Entry: {entry}")
        L.append(f"- Stop loss: {stop}")
        L.append(f"- Target: {target}")
        if rr is not None:
            L.append(f"- Reward:Risk: {rr}")
        if size is not None:
            L.append(f"- Position size (1% risk): {size}")
        L.append("")

    if debt_status or highlights:
        L.append("## Fundamentals")
        if debt_status:
            L.append(f"- {debt_status}")
        for h in (highlights or []):
            L.append(f"- {h}")
        L.append("")

    if news:
        L.append("## Recent news")
        for n in news:
            dot = _DOT.get(n.get("sentiment"), "")
            pub = n.get("publisher") or ""
            L.append(f"- {dot} {n.get('title')}" + (f" ({pub})" if pub else ""))
        L.append("")

    if thesis:
        L.append("## AI thesis")
        L.append(thesis)
        L.append("")

    L.append("---")
    L.append("*Educational analysis, not investment advice. Generated by EdgeForge.*")
    return "\n".join(L)
